name: flutter_boost_example
description: Demonstrates how to use the flutter_boost plugin.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dual_screen: ^1.0.4
  image_picker: ^1.1.2
  mime: ^1.0.5
  path_provider: ^2.1.3
  video_player: ^2.8.7
  webview_flutter: ^4.8.0

#  path_provider:
#    git:
#      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
#      path: "packages/path_provider/path_provider"
#  video_player:
#    git:
#      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
#      path: "packages/video_player/video_player"
#  webview_flutter:
#    git:
#      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
#      path: "packages/webview_flutter/webview_flutter"

  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '4.5.11'

  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter:
#    uses-material-design: true




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
